spring:
  h2:
    console:
      enabled: true
  session:
    timeout: 3600
    store-type: jdbc
    jdbc:
      initialize-schema: always
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 500
    open-in-view: false
    show-sql: true